services:
  - type: web
    name: traffic-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python detect.py
    envVars:
      - key: FLASK_ENV
        value: production
